% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function gobutton_descriptive_cat_proc(hObject, eventdata, h)

tool1 = get(h.descriptive_tool_1,'Value');
tool2 = get(h.descriptive_tool_2,'Value');
tool3 = get(h.descriptive_tool_3,'Value');

arr = [tool1, tool2, tool3];
selection_index = find(~arr); % Found the options that were selected

h.panel9 = uipanel(h.panel4,...
    'Title','A',...
    'Position',[.05 .78 .9 .2]);

h.cont_var1 = uicontrol(h.panel9 ,...
    'Style','text',...
    'String','Categorical Data',...
    'Units', 'normalized', ...
    'Position',[0.01 0.55 0.5 0.15]);

h.cont_var_val1= uicontrol(h.panel9 ,...
    'Style','pushbutton',...
    'String','Upload Data',...
    'Units', 'normalized', ...
    'Position',[0.45 0.55 0.25 0.2]);

h.cont_var_edit1 = uicontrol(h.panel9 ,...
    'Style','edit',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.755 0.55 0.15 0.2]);

h.group = uicontrol(h.panel9 ,...
    'Style','text',...
    'String','Grouping variable',...
    'Units', 'normalized', ...
    'Position',[0.01 0.25 0.5 0.15]);

h.group_var_upload = uicontrol(h.panel9 ,...
    'Style','pushbutton',...
    'String','Upload Data',...
    'Units', 'normalized', ...
    'Position',[0.45 0.25 0.25 0.2]);

h.group_var_edit = uicontrol(h.panel9 ,...
    'Style','edit',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.755 0.25 0.15 0.2]);

h.gobutton_tool_implement = uicontrol(h.panel4,...
    'Style','pushbutton',...
    'String','Proceed',...
    'Units', 'normalized', ...
    'Position',[0.1 0.01 0.8 0.04]);

% Button Callbacks
%------------------
set(h.cont_var_val1, 'callback',{@cont_var_val1_proc, h});
set(h.group_var_upload, 'callback',{@group_var_upload_proc, h});

set(h.gobutton_tool_implement, 'callback',{@descriptive_analysis_cat_proc, h ,selection_index});

guidata(hObject,h);

end