% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function gobutton_visualize_goproc_cat(hObject, eventdata, h)

tool_selection_cat = get(h.visual_plot_selection, 'Value'); % Selection of the plotting tools

h.panel9 = uipanel(h.panel4,...
    'Title','A',...
    'Position',[.05 .78 .9 .2]);


switch tool_selection_cat
    case 1
        % Bar plot
        
        h.cont_var = uicontrol(h.panel9 ,...
            'Style','text',...
            'String',' X (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.65 0.5 0.15]);
        
        h.cont_var_val= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.65 0.25 0.2]);
        
        h.cont_var_edit = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.65 0.15 0.2]);
        
        h.cont_var1 = uicontrol(h.panel9 ,...
            'Style','text',...
            'String','Y (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.30 0.5 0.15]);
        
        h.cont_var_val1= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.30 0.25 0.2]);
        
        h.cont_var_edit1 = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.30 0.15 0.2]);
        
        h.gobutton_tool_implement = uicontrol(h.panel4,...
            'Style','pushbutton',...
            'String','Proceed',...
            'Units', 'normalized', ...
            'Position',[0.1 0.01 0.8 0.04]);
        
        % Button Callbacks
        %------------------
        set(h.cont_var_val, 'callback',{@cont_var_val_proc, h});
        set(h.cont_var_val1, 'callback',{@cont_var_val1_proc, h});
        set(h.gobutton_tool_implement, 'callback',{@gobutton_tool_implement_proc_bar, h});
        
    case 2
        % Line plot
        
        h.cont_var = uicontrol(h.panel9 ,...
            'Style','text',...
            'String',' X (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.65 0.5 0.15]);
        
        h.cont_var_val= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.65 0.25 0.2]);
        
        h.cont_var_edit = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.65 0.15 0.2]);
        
        h.cont_var1 = uicontrol(h.panel9 ,...
            'Style','text',...
            'String','Y (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.30 0.5 0.15]);
        
        h.cont_var_val1= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.30 0.25 0.2]);
        
        h.cont_var_edit1 = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.30 0.15 0.2]);
        
        h.gobutton_tool_implement = uicontrol(h.panel4,...
            'Style','pushbutton',...
            'String','Proceed',...
            'Units', 'normalized', ...
            'Position',[0.1 0.01 0.8 0.04]);
        
        % Button Callbacks
        %------------------
        set(h.cont_var_val, 'callback',{@cont_var_val_proc, h});
        set(h.cont_var_val1, 'callback',{@cont_var_val1_proc, h});
        set(h.gobutton_tool_implement, 'callback',{@gobutton_tool_implement_proc_line, h});
        
    case 3
        % Stack chart
        
        h.cont_var = uicontrol(h.panel9 ,...
            'Style','text',...
            'String',' X (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.65 0.5 0.15]);
        
        h.cont_var_val= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.65 0.25 0.2]);
        
        h.cont_var_edit = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.65 0.15 0.2]);
        
        h.cont_var1 = uicontrol(h.panel9 ,...
            'Style','text',...
            'String','Y (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.30 0.5 0.15]);
        
        h.cont_var_val1= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.30 0.25 0.2]);
        
        h.cont_var_edit1 = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.30 0.15 0.2]);
        
        h.gobutton_tool_implement = uicontrol(h.panel4,...
            'Style','pushbutton',...
            'String','Proceed',...
            'Units', 'normalized', ...
            'Position',[0.1 0.01 0.8 0.04]);
        
        % Button Callbacks
        %------------------
        set(h.cont_var_val, 'callback',{@cont_var_val_proc, h});
        set(h.cont_var_val1, 'callback',{@cont_var_val1_proc, h});
        set(h.gobutton_tool_implement, 'callback',{@gobutton_tool_implement_proc_stack, h});
        
        
    case 4
        % Pie chart
        
        h.cont_var = uicontrol(h.panel9 ,...
            'Style','text',...
            'String',' Categorical Data',...
            'Units', 'normalized', ...
            'Position',[0.01 0.65 0.5 0.15]);
        
        h.cont_var_val= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.65 0.25 0.2]);
        
        h.cont_var_edit = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.65 0.15 0.2]);                
        
        h.gobutton_tool_implement = uicontrol(h.panel4,...
            'Style','pushbutton',...
            'String','Proceed',...
            'Units', 'normalized', ...
            'Position',[0.1 0.01 0.8 0.04]);
        
        % Button Callbacks
        %------------------
        set(h.cont_var_val, 'callback',{@cont_var_val_proc, h});
        % set(h.cont_var_val1, 'callback',{@cont_var_val1_proc, h});
        set(h.gobutton_tool_implement, 'callback',{@gobutton_tool_implement_proc_pie, h});
        
    case 5
        % Box and Whisker plot
        
        h.cont_var = uicontrol(h.panel9 ,...
            'Style','text',...
            'String',' X (Categorical)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.65 0.5 0.15]);
        
        h.cont_var_val= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.65 0.25 0.2]);
        
        h.cont_var_edit = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.65 0.15 0.2]);
        
        h.cont_var1 = uicontrol(h.panel9 ,...
            'Style','text',...
            'String','Y (Continuous)',...
            'Units', 'normalized', ...
            'Position',[0.01 0.30 0.5 0.15]);
        
        h.cont_var_val1= uicontrol(h.panel9 ,...
            'Style','pushbutton',...
            'String','Upload Data',...
            'Units', 'normalized', ...
            'Position',[0.45 0.30 0.25 0.2]);
        
        h.cont_var_edit1 = uicontrol(h.panel9 ,...
            'Style','edit',...
            'String',' ',...
            'Units', 'normalized', ...
            'Position',[0.755 0.30 0.15 0.2]);
        
        h.gobutton_tool_implement = uicontrol(h.panel4,...
            'Style','pushbutton',...
            'String','Proceed',...
            'Units', 'normalized', ...
            'Position',[0.1 0.01 0.8 0.04]);
        
        % Button Callbacks
        %------------------
        set(h.cont_var_val, 'callback',{@cont_var_val_proc, h});
        set(h.cont_var_val1, 'callback',{@cont_var_val1_proc, h});
        set(h.gobutton_tool_implement, 'callback',{@gobutton_tool_implement_proc_box, h});
        
    otherwise
        % Do Nothing
end

guidata(hObject,h);

end