% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function nonlin_regress(hObject, eventdata, h, inp_independent, inp_dependent, label_name_independent,label_name_dependent)

% Delete existing handles
%-------------------------------
panel11_label = findall(h.panel4,'title', 'C');
delete(panel11_label);

% Initialize Handles for Inputs
%-------------------------------
h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .27 .9 .3]);
    
h.writeequation = uicontrol(h.panel11,...
    'Style','text',...
    'String','Model Function',...
    'Units', 'normalized', ...
    'Position',[0.01 0.8 0.3 0.1]);

h.writeequationvalue = uicontrol(h.panel11,...
    'Style','edit',...
    'String','',...
    'Units', 'normalized', ...
    'Position',[0.3 0.8 0.6 0.15]);

h.betavaluelabel= uicontrol(h.panel11,...
    'Style','text',...
    'String','Beta Values',...
    'Units', 'normalized', ...
    'Position',[0.01 0.50 0.3 0.1]);

h.betavalue= uicontrol(h.panel11,...
    'Style','edit',...
    'String','',...
    'Units', 'normalized', ...
    'Position',[0.3 0.50 0.6 0.15]);

h.run2button= uicontrol(h.panel4,...
    'Style','pushbutton',...
    'String','Run',...
    'Units', 'normalized', ...
    'Position',[0.2 0.025 0.6 0.035]);

set(h.run2button, 'callback',{@run2buttonprocedure, h, inp_independent, inp_dependent, label_name_independent,label_name_dependent});

guidata(hObject,h);

end
