% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedprocprocedure_sample(hObject, eventdata, h)

% Get handles for initializing variables
%-------------------------------------------------------------------------
proportions_large = get(h.proportionlargesample, 'Value');
proportions_small = get(h.proportionsmallsample, 'Value');

% Decision Algorithms
%-------------------------------------------------------------------------

if proportions_large == 1 && proportions_small == 0
    
    % Large sample proportions
    %---------------------------
    
    h.radiogroup4 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.03 0.90 0.6]);
    
    h.totalsamplessample1 = uicontrol(h.radiogroup4,...
        'Style','text',...
        'String','Total Outcomes (Sample 1)',...
        'Units', 'normalized', ...
        'Position',[0.01 0.70 0.5 0.20]);
    
    h.totalsamplessample1val = uicontrol(h.radiogroup4,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.5 0.80 0.4 0.15]);
    
    h.totalsamplessample2 = uicontrol(h.radiogroup4,...
        'Style','text',...
        'String','Total Outcomes (Sample 2)',...
        'Units', 'normalized', ...
        'Position',[0.01 0.56 0.5 0.20]);
    
    h.totalsamplessample2val = uicontrol(h.radiogroup4,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.5 0.63 0.4 0.15]);
    
    h.favoutcomessample1 = uicontrol(h.radiogroup4,...
        'Style','text',...
        'String','Favourable Outcomes (Sample 1)',...
        'Units', 'normalized', ...
        'Position',[0.03 0.40 0.4 0.20]);
    
    h.favoutcomessample1val = uicontrol(h.radiogroup4,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.5 0.45 0.4 0.15]);
    
    h.favoutcomessample2 = uicontrol(h.radiogroup4,...
        'Style','text',...
        'String','Favourable Outcomes (Sample 2)',...
        'Units', 'normalized', ...
        'Position',[0.03 0.20 0.4 0.20]);
    
    h.favoutcomessample2val = uicontrol(h.radiogroup4,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.5 0.25 0.4 0.15]);
    
    h.alphavallabel = uicontrol(h.radiogroup4,...
        'Style','text',...
        'String','Alpha value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.05 0.4 0.1]);
    
    h.alphaval = uicontrol(h.radiogroup4,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.5 0.05 0.4 0.15]);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Checkbox Callback functions
    %---------------------------------------------------------------------
    set(h.rundata, 'callback',{@rundatatwosampleproc, h});
    
elseif proportions_large == 0 && proportions_small == 1
    
    % Small sample proportions
    %---------------------------
    
    h.radiogroup4 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.03 0.90 0.6]);
    
    h.cat1 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Categorical Data 1',...
        'Units', 'normalized', ...
        'Position',[0.01 0.80 0.5 0.1]);
    
    h.cat1val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.75 0.25 0.2]);
    
    h.cat2 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Categorical Data 2',...
        'Units', 'normalized', ...
        'Position',[0.01 0.60 0.5 0.1]);
    
    h.cat2val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.55 0.25 0.2]);
    
    h.cat1value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.75 0.15 0.2]);
    
    h.cat2value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.55 0.15 0.2]);
    
    h.alphavallabel = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Alpha value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.35 0.4 0.1]);
    
    h.alphaval = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.25 0.15]);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Checkbox Callback functions
    %---------------------------------------------------------------------
    set(h.cat1val, 'callback',{@cat1valuploaddataproc, h});
    set(h.cat2val, 'callback',{@cat2valuploaddataproc, h});
    set(h.rundata, 'callback',{@rundatatwosampleprocsmall, h});
    
else
    % Do Nothing
end

end