% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India


function proceedbuttonprocregressionmatching(hObject, eventdata, h)

valuesample4 = get(h.sample4, 'Value');
valuesample5 = get(h.sample5, 'Value');

if valuesample4 == 1 && valuesample5 == 0
    % Matching Done
    
    % Delete existing handles
    %----------------------------------------------
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf(' Matching Done \n');
    fprintf('------------------- \n');
    
    % Conditional Logistic Regression
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.uploaddependentvar = uicontrol(h.panel11,...
        'Style','text',...
        'String','Dependent Variable',...
        'Units', 'normalized', ...
        'Position',[0.01 0.80 0.5 0.1]);
    
    h.uploaddependentvarstr = uicontrol(h.panel11 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.83 0.25 0.1]);
    
    h.uploaddependentvarstrlabel = uicontrol(h.panel11 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.83 0.15 0.1],...
        'Max', 100);
    
    h.uploadindependentvar = uicontrol(h.panel11,...
        'Style','text',...
        'String','Independent Variables',...
        'Units', 'normalized', ...
        'Position',[0.01 0.68 0.5 0.1]);
    
    h.uploadindependentvarstr = uicontrol(h.panel11 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.71 0.25 0.1]);
    
    h.uploadindependentvarstrlabel = uicontrol(h.panel11 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.71 0.15 0.1],...
        'Max', 100);
    
    h.uploadgroupvar= uicontrol(h.panel11,...
        'Style','text',...
        'String','Group Variables',...
        'Units', 'normalized', ...
        'Position',[0.01 0.56 0.5 0.1]);
    
    h.uploadgroupvarstr = uicontrol(h.panel11 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.59 0.25 0.1]);
    
    h.uploadgroupvarstrlabel = uicontrol(h.panel11 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.59 0.15 0.1],...
        'Max', 100);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    
    % Button Functions
    %-----------------------------------------------------------------------
    set(h.uploaddependentvarstr, 'callback',{@uploaddependentvarstrproc, h});
    set(h.uploadindependentvarstr, 'callback',{@uploadindependentvarstrproc, h});
    set(h.uploadgroupvarstr, 'callback',{@uploadgroupvarstrproc, h});
    set(h.rundata, 'callback',{@runconditionallogit, h});
   
    
elseif valuesample4 == 0 && valuesample5 == 1
    % Matching not Done
    
    % Delete existing handles
    %----------------------------------------------
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf(' Matching Not Done \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.uploaddependentvar = uicontrol(h.panel11,...
        'Style','text',...
        'String','Dependent Variable',...
        'Units', 'normalized', ...
        'Position',[0.01 0.80 0.5 0.1]);
    
    h.uploaddependentvarstr = uicontrol(h.panel11 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.83 0.25 0.1]);
    
    h.uploaddependentvarstrlabel = uicontrol(h.panel11 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.83 0.15 0.1],...
        'Max', 100);
    
    h.uploadindependentvar = uicontrol(h.panel11,...
        'Style','text',...
        'String','Independent Variables',...
        'Units', 'normalized', ...
        'Position',[0.01 0.68 0.5 0.1]);
    
    h.uploadindependentvarstr = uicontrol(h.panel11 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.71 0.25 0.1]);
    
    h.uploadindependentvarstrlabel = uicontrol(h.panel11 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.71 0.15 0.1],...
        'Max', 100);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Button Functions
    %-----------------------------------------------------------------------
    set(h.uploaddependentvarstr, 'callback',{@uploaddependentvarstrproc, h});
    set(h.uploadindependentvarstr, 'callback',{@uploadindependentvarstrproc, h});
    set(h.rundata, 'callback',{@rundataproccatregressionlogistic, h});
    
else
    % Do Nothing
end
guidata(hObject,h);
end