% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedvariance(hObject, eventdata, h)

% Initialize variable
%------------------------------------------------
variance_unknown = get(h.var_unknown, 'Value');
variance_known = get(h.var_known, 'Value');

% Determine if variance is known or not
%------------------------------------------------
if variance_unknown == 1 && variance_known == 0
    % Population variance is not known (Default mode)
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.radiogroup2 = uibuttongroup(h.panel10,...
        'Units','normalized',...
        'Position', [0.05 0.07 0.90 0.9]);
    
    h.sample1 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    One Sample Analysis',...
        'Units', 'normalized', ...
        'Position',[0.25 0.75 0.92 0.2],'HandleVisibility','off');
    
    h.sample2 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    Two Sample Analysis',...
        'Units', 'normalized', ...
        'Position',[0.25 0.55 0.92 0.2],'HandleVisibility','off');
    
    h.sample3 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    > 2 Sample Analysis',...
        'Units', 'normalized', ...
        'Position',[0.25 0.35 0.92 0.2],'HandleVisibility','off');
    
    h.proceedbutton = uicontrol(h.radiogroup2 ,'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.10 0.4 0.2]);
    
    % Button Function
    %------------------
    set(h.proceedbutton, 'callback',{@proceedbuttonprocmean, h});
    
elseif variance_unknown == 0 && variance_known == 1
    % Population variance is known
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.radiogroup2 = uibuttongroup(h.panel10,...
        'Units','normalized',...
        'Position', [0.05 0.07 0.90 0.9]);
    
    h.sample1 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    One Sample Analysis',...
        'Units', 'normalized', ...
        'Position',[0.25 0.75 0.92 0.2],'HandleVisibility','off');
    
    h.sample2 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    Two Sample Analysis',...
        'Units', 'normalized', ...
        'Position',[0.25 0.55 0.92 0.2],'HandleVisibility','off');
      
    h.proceedbutton = uicontrol(h.radiogroup2 ,'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.10 0.4 0.2]);
    
    % Button Function
    %------------------
    set(h.proceedbutton, 'callback',{@proceedbuttonprocmean_var_known, h});
    
else
    % Do Nothing
    
end

end