% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedbuttonprocsurvival(hObject, eventdata, h)

% Initialize Variables
%------------------------------------------------------------------------
valuesample1 = get(h.sample1, 'Value');
valuesample2 = get(h.sample2, 'Value');

% Decision Algorithm
%------------------------------------------------------------------------
if valuesample1 == 1 && valuesample2 == 0
    % KM for Overall Data
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf('Kaplan Meier : Overall Data \n');
    fprintf('------------------- \n');
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.timevariable = uicontrol(h.panel10,...
        'Style','text',...
        'String','Survival Time',...
        'Units', 'normalized', ...
        'Position',[0.05 0.60 0.3 0.2]);
    
    h.timevariableval = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
    h.statusvariable = uicontrol(h.panel10,...
        'Style','text',...
        'String','Karnovsky Scores',...
        'Units', 'normalized', ...
        'Position',[0.05 0.30 0.3 0.3]);
    
    h.statusvariableval = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.42 0.3 0.2]);
    
    h.timevariablevallabel = uicontrol(h.panel10 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.63 0.1 0.2]);
    
    h.statusvariablelabel = uicontrol(h.panel10,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.42 0.1 0.2]);
    
    h.rundata = uicontrol(h.panel4 ,'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    
    % Button Functions
    %--------------------------------------------------------------------
    set(h.timevariableval, 'callback',{@timevariablevalproc, h});
    set(h.statusvariableval, 'callback',{@statusvariablevalproc, h});
    set(h.rundata, 'callback',{@rundataprocsurvival, h});
    
elseif valuesample1 == 0 && valuesample2 == 1
    % KM for Subset Data
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf('Kaplan Meier : Subset Data \n');
    fprintf('------------------- \n');
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.timevariable = uicontrol(h.panel10 ,...
        'Style','text',...
        'String','Survival Time',...
        'Units', 'normalized', ...
        'Position',[0.05 0.60 0.3 0.2]);
    
    h.timevariableval = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
%     h.statusvariable = uicontrol(h.panel10 ,...
%         'Style','text',...
%         'String','Status Variable',...
%         'Units', 'normalized', ...
%         'Position',[0.05 0.30 0.3 0.3]);
%     
%     h.statusvariableval = uicontrol(h.panel10 ,...
%         'Style','pushbutton',...
%         'String','Upload',...
%         'Units', 'normalized', ...
%         'Position',[0.45 0.42 0.3 0.2]);
    
    h.groupvariable = uicontrol(h.panel10 ,...
        'Style','text',...
        'String','Group Variable',...
        'Units', 'normalized', ...
        'Position',[0.05 0.18 0.3 0.2]);
    
    h.groupvariableval = uicontrol(h.panel10,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.20 0.3 0.2]);
    
    h.timevariablevallabel = uicontrol(h.panel10 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.63 0.1 0.2]);
    
%     h.statusvariablelabel = uicontrol(h.panel10 ,...
%         'Style','edit',...
%         'String',' ',...
%         'Units', 'normalized', ...
%         'Position',[0.77 0.42 0.1 0.2]);
    
    h.groupvariablelabel = uicontrol(h.panel10 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.20 0.1 0.2]);
    
    h.rundata = uicontrol(h.panel4 ,'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Button Functions
    %-------------------------------------------------------------
    set(h.timevariableval, 'callback',{@timevariablevalproc, h});
    % set(h.statusvariableval, 'callback',{@statusvariablevalproc, h});
    set(h.groupvariableval, 'callback',{@groupvariablevalproc, h});
    set(h.rundata, 'callback',{@rundataprocsurvivalsubset, h});
    
else
    % Do Nothing
end
guidata(hObject,h)
end