% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedbuttonprocmean_var_known(hObject, eventdata, h)

% Initializing Variables
%-----------------------
valuesample1 = get(h.sample1, 'Value');
valuesample2 = get(h.sample2, 'Value');

% Decision Algorithm
%-----------------------
if valuesample1 == 1 && valuesample2 == 0
    
    % One sample analysis
    %-----------------------
    % Delete existing handles
    %----------------------------------------------
    
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf('One Sample Analysis \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup3 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.5 0.90 0.5]);
    
    h.meanvallabel = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Mean Value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.65 0.5 0.2]);
    
    h.meanval = uicontrol(h.radiogroup3,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.45 0.72 0.3 0.15]);
    
    h.stdvallabel = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','STD Value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.42 0.5 0.2]);
    
    h.stdval = uicontrol(h.radiogroup3,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.45 0.50 0.3 0.15]);
    
    h.uploaddatastring = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.01 0.10 0.5 0.3]);
    
    h.uploaddata = uicontrol(h.radiogroup3 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.25 0.3 0.2]);
    
    h.uploaddatalabel = uicontrol(h.radiogroup3 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.76 0.25 0.2 0.2]);
    
    h.rundata = uicontrol(h.panel4 ,'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Button Callbacks
    %------------------
    set(h.uploaddata, 'callback',{@uploaddatonesammean, h});
    set(h.rundata, 'callback',{@rundataprocmean_onesample, h});
    
elseif valuesample1 == 0 && valuesample2 == 1
    
    % Two sample analysis
    %-----------------------
    % Delete existing handles
    %----------------------------------------------
    
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf('Two Sample Analysis \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup3 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.6 0.90 0.4]);
    
%     h.meanvallabel = uicontrol(h.radiogroup3,...
%         'Style','text',...
%         'String','Mean Value',...
%         'Units', 'normalized', ...
%         'Position',[0.01 0.65 0.5 0.2]);
%     
%     h.meanval = uicontrol(h.radiogroup3,...
%         'Style','edit',...
%         'String','',...
%         'Units', 'normalized', ...
%         'Position',[0.45 0.72 0.3 0.15]);
%     
%     h.stdvallabel = uicontrol(h.radiogroup3,...
%         'Style','text',...
%         'String','STD Value',...
%         'Units', 'normalized', ...
%         'Position',[0.01 0.42 0.5 0.2]);
%     
%     h.stdval = uicontrol(h.radiogroup3,...
%         'Style','edit',...
%         'String','',...
%         'Units', 'normalized', ...
%         'Position',[0.45 0.50 0.3 0.15]);
    
    h.uploaddatastring = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Upload Data 1',...
        'Units', 'normalized', ...
        'Position',[0.01 0.50 0.5 0.3]);
    
    h.uploaddata = uicontrol(h.radiogroup3 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
    h.uploaddatalabel = uicontrol(h.radiogroup3 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.76 0.65 0.2 0.2]);
    
    h.uploaddatastring1 = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Upload Data 2',...
        'Units', 'normalized', ...
        'Position',[0.01 0.30 0.5 0.2]);
    
    h.uploaddata1 = uicontrol(h.radiogroup3 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.3 0.2]);
    
    h.uploaddatalabel1 = uicontrol(h.radiogroup3 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.76 0.35 0.2 0.2]);
    
    h.rundata = uicontrol(h.radiogroup3 ,'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.10 0.4 0.18]);
    
    % Button Callbacks
    %------------------
    set(h.uploaddata, 'callback',{@uploaddatonesammean, h});
    set(h.uploaddata1, 'callback',{@uploaddatonesammean1, h});
    set(h.rundata, 'callback',{@rundataprocmean_twosample, h});
    
else
    % Do Nothing
end

guidata(hObject,h);

end