% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedbuttonprocmean(hObject, eventdata, h)

% Initializing Variables
%-----------------------
valuesample1 = get(h.sample1, 'Value');
valuesample2 = get(h.sample2, 'Value');
valuesample3 = get(h.sample3, 'Value');

% Decision Algorithms
%-----------------------
if valuesample1 == 1 && valuesample2 == 0 && valuesample3 == 0
    
    % One Sample Analysis
    %---------------------
    
    % Delete existing handles
    %----------------------------------------------
    % panel10_label = findall(h.panel4,'title', 'B');
    % delete(panel10_label);
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    
    fprintf('------------------- \n');
    fprintf('One Sample Analysis \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup3 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.7 0.90 0.3]);
    
    h.hypothetical = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Hypothetical Value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.65 0.5 0.2]);
    
    h.hypotheticalvalue = uicontrol(h.radiogroup3,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.3]);
    
    h.uploaddatastring = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.01 0.20 0.5 0.3]);
    
    h.uploaddata = uicontrol(h.radiogroup3 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.30 0.3 0.3]);
    
    h.uploaddatalabel = uicontrol(h.radiogroup3 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.76 0.30 0.2 0.3]);
    
    h.rundata = uicontrol(h.panel4 ,'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Button Callbacks
    %------------------
    set(h.uploaddata, 'callback',{@uploaddatonesammean, h});
    set(h.rundata, 'callback',{@rundataprocmeanone, h});
    
elseif valuesample1 == 0 && valuesample2 == 1 && valuesample3 == 0
    
    % Two Sample Analysis
    %---------------------
    
    % Delete existing handles
    %----------------------------------------------
    % panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    % delete(panel10_label);
    delete(panel11_label);
    
    
    fprintf('------------------- \n');
    fprintf('Two Sample Analysis \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup3 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.7 0.90 0.3]);
    
    h.pairedoption = uicontrol(h.radiogroup3,...
        'Style','radiobutton',...
        'String','    Paired Sample',...
        'Units', 'normalized', ...
        'Position',[0.25 0.75 0.92 0.2],'HandleVisibility','off');
    
    h.independentoption = uicontrol(h.radiogroup3,...
        'Style','radiobutton',...
        'String','    Independent Sample',...
        'Units', 'normalized', ...
        'Position',[0.25 0.50 0.92 0.2],'HandleVisibility','off');
    
    h.proceeddata = uicontrol(h.radiogroup3 ,'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.10 0.4 0.2]);
    
    % Button Callbacks
    %------------------
    set(h.proceeddata, 'callback',{@proceeddatamean2, h});
    
elseif valuesample1 == 0 && valuesample2 == 0 && valuesample3 == 1
    
    % > (more) Two Sample Analysis
    %---------------------
    
    % Delete existing handles
    %----------------------------------------------
    % panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    % delete(panel10_label);
    delete(panel11_label);
    
    
    fprintf('------------------- \n');
    fprintf(' > Two Sample Analysis \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup3 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.4 0.90 0.6]);
    
    h.uploaddatastring = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Numerical Data',...
        'Units', 'normalized', ...
        'Position',[0.05 0.60 0.3 0.2]);
    
    h.uploaddata = uicontrol(h.radiogroup3 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.7 0.3 0.15]);
    
    h.uploaddatalabel = uicontrol(h.radiogroup3 ,...
        'Style','edit',...
        'String','','Max',600,'HorizontalAlignment','left',...
        'Units', 'normalized', ...
        'Position',[0.77 0.700 0.2 0.15]);
    
    h.uploaddatastringcat = uicontrol(h.radiogroup3,...
        'Style','text',...
        'String','Categorical Data',...
        'Units', 'normalized', ...
        'Position',[0.05 0.3 0.3 0.3]);
    
    h.uploaddatacat = uicontrol(h.radiogroup3 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.5 0.3 0.15]);
    
    h.uploaddatalabelcat = uicontrol(h.radiogroup3 ,...
        'Style','edit',...
        'String','','Max',600,'HorizontalAlignment','left',...
        'Units', 'normalized', ...
        'Position',[0.77 0.5 0.2 0.15]);
    
    h.samples_related= uicontrol(h.radiogroup3 ,...
        'Style','text',...
        'String',' Are the samples related ?',...
        'Units', 'normalized', ...
        'Position',[0.05 0.15 0.45 0.25]);
    
    h.sample_popup = uicontrol(h.radiogroup3 ,...
        'Style', 'popup', ...
        'Units', 'normalized', ...
        'Position', [0.55, 0.32, 0.4, 0.1], ...
        'String', {'Yes','No'});
    
    h.rundata = uicontrol(h.radiogroup3 ,'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.05 0.4 0.13]);
    
    % Button Callbacks
    %------------------
    set(h.uploaddatacat, 'callback',{@uploaddatacatmeanmore2cat, h});
    set(h.uploaddata, 'callback',{@uploaddataprocmeanmore2, h});
    set(h.rundata, 'callback',{@rundataprocmeanmore2option, h});
    
else
    % Do Nothing
end

guidata(hObject,h);

end