% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedprocprocedure(hObject, eventdata, h)

% Get handles for initializing variables
%-------------------------------------------------------------------------
proportions_unpaired = get(h.proportionunpaired, 'Value');
proportion_paired = get(h.proportionpaired, 'Value');

% Decision Algorithms
%-------------------------------------------------------------------------
if proportions_unpaired == 1 && proportion_paired == 0
    
    % Unpaired Proportion
    %---------------------
    
    % Delete existing handles
    %----------------------------------------------
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf('Unpaired Proportions \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    %     h.radiogroup3 = uibuttongroup(h.panel11,...
    %         'Units','normalized',...
    %         'Position', [0.05 0.65 0.90 0.35]);
    %
    %     h.proportionlargesample = uicontrol(h.radiogroup3,...
    %         'Style','radiobutton',...
    %         'String',' Large samples',...
    %         'Units', 'normalized', ...
    %         'Position',[0.25 0.75 0.92 0.2],...
    %         'HandleVisibility','off');
    %
    %     h.proportionsmallsample = uicontrol(h.radiogroup3,...
    %         'Style','radiobutton',...
    %         'String',' Small samples',...
    %         'Units', 'normalized', ...
    %         'Position',[0.25 0.50 0.92 0.2],...
    %         'HandleVisibility','off');
    %
    %     h.proceedproc = uicontrol(h.radiogroup3,...
    %         'Style','pushbutton',...
    %         'String','Proceed',...
    %         'Units', 'normalized', ...
    %         'Position',[0.25 0.10 0.4 0.2]);
    %
    %     set(h.proceedproc, 'callback',{@proceedprocprocedure_sample, h});
    
    h.radiogroup4 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.4 0.90 0.6]);
    
    h.cat1 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Categorical Data 1',...
        'Units', 'normalized', ...
        'Position',[0.01 0.80 0.5 0.1]);
    
    h.cat1val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.75 0.25 0.2]);
    
    h.cat2 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Categorical Data 2',...
        'Units', 'normalized', ...
        'Position',[0.01 0.60 0.5 0.1]);
    
    h.cat2val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.55 0.25 0.2]);
    
    h.cat1value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.75 0.15 0.2]);
    
    h.cat2value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.55 0.15 0.2]);
    
    h.alphavallabel = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Alpha value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.35 0.4 0.1]);
    
    h.alphaval = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.25 0.15]);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Checkbox Callback functions
    %---------------------------------------------------------------------
    set(h.cat1val, 'callback',{@cat1valuploaddataproc, h});
    set(h.cat2val, 'callback',{@cat2valuploaddataproc, h});
    set(h.rundata, 'callback',{@rundatatwosampleprocsmall, h});
    
    
elseif proportions_unpaired == 0 && proportion_paired == 1
    
    % Paired Proportion
    %-----------------
    
    % Delete existing handles
    %----------------------------------------------
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    fprintf('------------------- \n');
    fprintf('Paired Proportions \n');
    fprintf('------------------- \n');
    
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup4 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.60 0.90 0.4]);
    
    h.cat1 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Nominal Data 1',...
        'Units', 'normalized', ...
        'Position',[0.01 0.80 0.5 0.1]);
    
    h.cat1val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.75 0.25 0.2]);
    
    h.cat2 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Nominal Data 2',...
        'Units', 'normalized', ...
        'Position',[0.01 0.50 0.5 0.1]);
    
    h.cat2val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.45 0.25 0.2]);
    
    h.cat1value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.72 0.15 0.2]);
    
    h.cat2value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.43 0.15 0.2]);
    
    %     h.alphavallabel = uicontrol(h.radiogroup4 ,...
    %         'Style','text',...
    %         'String','Alpha value',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.35 0.4 0.1]);
    %
    %     h.alphaval = uicontrol(h.radiogroup4 ,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.45 0.35 0.25 0.15]);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Checkbox Callback functions
    %---------------------------------------------------------------------
    set(h.cat1val, 'callback',{@cat1valuploaddataproc, h});
    set(h.cat2val, 'callback',{@cat2valuploaddataproc, h});
    set(h.rundata, 'callback',{@rundatatwosampleproc_paired, h});
    
else
    % Do Nothing
end

guidata(hObject,h)

end