% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedbuttonproc1(hObject, eventdata, h)

% Initialize Variables
%-------------------------------------------------------------------------
continuouslabelval = get(h.continuouslabel, 'Value');
discretelabelval = get(h.discretelabel, 'Value');

if continuouslabelval == 1 && discretelabelval == 0
    % Continuous Options
    %-------------------------------------------------------------------------
    
    % Delete previous panel 4 details
    %-------------------------------------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    delete(panel10_label);

    h.panel9 = uipanel(h.panel4,...
        'Title','A',...
        'Position',[.05 .78 .9 .2]);
    
    
    h.sample1 = uicontrol(h.panel9,...
        'Style', 'popup', ...
        'Units',    'pixels', ...
        'Units', 'normalized', ...
        'Position', [0.04 0.75 0.92 0.2], ...
        'String', {'Mean','Standard Deviation','Median','Inter-Quartile Range','Histogram','Line Chart','Box Plot','Scatter Plot'});
    
    h.browsecol = uicontrol(h.panel9 ,'Style','text',...
        'String','Data',...
        'Units', 'normalized', ...
        'Position',[0.01 0.20 0.3 0.3]);
    
    h.browsecolbutton = uicontrol(h.panel9 ,'Style','pushbutton',...
        'String','Browse',...
        'Units', 'normalized', ...
        'Position',[0.3 0.35 0.3 0.2]);
    
    h.browselabel = uicontrol(h.panel9 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.65 0.35 0.2 0.2]);
    
    h.proceedbutton1 = uicontrol(h.panel4 ,'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    set(h.browsecolbutton, 'callback', {@browsecolbuttonproc, h});
    set(h.proceedbutton1, 'callback', {@proceedbutton2proc, h});
    
    
elseif continuouslabelval == 0 && discretelabelval == 1
    % Discrete Options
    %-------------------------------------------------------------------------
    
    % Delete previous panel 4 details
    %-------------------------------------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    delete(panel10_label);
    
    h.panel9 = uipanel(h.panel4,...
        'Title','A',...
        'Position',[.05 .78 .9 .2]);
    
    h.sample1 = uicontrol(h.panel9,...
        'Style', 'popup', ...
        'Units',    'pixels', ...
        'Units', 'normalized', ...
        'Position', [0.04 0.75 0.92 0.2], ...
        'String', {'Frequency','Percentage','Mode','Bar Chart','Pie Chart','Stack Chart'});
    
    h.browsecol = uicontrol(h.panel9 ,'Style','text',...
        'String','Data',...
        'Units', 'normalized', ...
        'Position',[0.01 0.20 0.3 0.3]);
    
    h.browsecolbutton = uicontrol(h.panel9 ,'Style','pushbutton',...
        'String','Browse',...
        'Units', 'normalized', ...
        'Position',[0.3 0.35 0.3 0.2]);
    
    h.browselabel = uicontrol(h.panel9 ,'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.65 0.35 0.2 0.2]);
    
    h.proceedbutton1 = uicontrol(h.panel4 ,'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    set(h.browsecolbutton, 'callback', {@browsecolbuttonproc, h});
    set(h.proceedbutton1, 'callback', {@proceedbutton1proc, h});
    
else
    % Do Nothing
end
guidata(hObject,h);
end