% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedbuttonprocregression(hObject, eventdata, h)

% Initialize Variables
%--------------------------------------
valuesample1 = get(h.sample1, 'Value');
valuesample2 = get(h.sample2, 'Value');
% valuesample3 = get(h.sample3, 'Value');

% Decision Loop
%------------------------------------------------------------
if valuesample1 == 1 && valuesample2 == 0
    % Continuous Data
    %--------------------------------------------
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.uploaddependentvar = uicontrol(h.panel10,...
        'Style','text',...
        'String','Dependent Variable',...
        'Units', 'normalized', ...
        'Position',[0.01 0.60 0.4 0.2]);
    
    h.uploaddependentvarstr = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
    h.uploaddependentvarstrlabel = uicontrol(h.panel10,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.65 0.1 0.2],...
        'Max', 100);
    
    h.uploadindependentvar = uicontrol(h.panel10,...
        'Style','text',...
        'String','Independent Variables',...
        'Units', 'normalized', ...
        'Position',[0.01 0.20 0.4 0.3]);
    
    h.uploadindependentvarstr = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.3 0.2]);
    
    h.uploadindependentvarstrlabel = uicontrol(h.panel10 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.35 0.1 0.2],...
        'Max', 100);
    
    h.rundata = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.05 0.4 0.2]);
    
    % Button Functions
    %------------------------------------------------------------------------
    set(h.uploaddependentvarstr, 'callback',{@uploaddependentvarstrproc, h});
    set(h.uploadindependentvarstr, 'callback',{@uploadindependentvarstrproc, h});
    set(h.rundata, 'callback',{@rundataproccontregression, h});
    
elseif valuesample1 == 0 && valuesample2 == 1
    % Categorical Data
    %-----------------------------------------------
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.radiogroup2 = uibuttongroup(h.panel10,...
        'Units','normalized',...
        'Position', [0.05 0.07 0.90 0.9]);
    
    h.sample4 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    Matching Done',...
        'Units', 'normalized', ...
        'Position',[0.25 0.75 0.92 0.2],'HandleVisibility','off');
    
    h.sample5 = uicontrol(h.radiogroup2,...
        'Style','radiobutton',...
        'String','    Matching Not Done',...
        'Units', 'normalized', ...
        'Position',[0.25 0.50 0.92 0.2],'HandleVisibility','off');
    
    h.proceedbutton = uicontrol(h.radiogroup2 ,...
        'Style','pushbutton',...
        'String','Proceed',...
        'Units', 'normalized', ...
        'Position',[0.25 0.10 0.4 0.2]);
    
    set(h.proceedbutton, 'callback',{@proceedbuttonprocregressionmatching, h});
    
    % elseif valuesample1 == 0 && valuesample2 == 0 && valuesample3 == 1
    %     % Time to an Event
    %     %----------------------------------
    %
    %     % Delete existing handles
    %     %----------------------------------------------
    %     panel10_label = findall(h.panel4,'title', 'B');
    %     panel11_label = findall(h.panel4,'title', 'C');
    %     delete(panel10_label);
    %     delete(panel11_label);
    %
    %     h.panel10 = uipanel(h.panel4,...
    %         'Title','B',...
    %         'Position',[.05 .58 .9 .2]);
    %
    %     h.uploaddependentvar = uicontrol(h.panel10,...
    %         'Style','text',...
    %         'String','Time Variable',...
    %         'Units', 'normalized', ...
    %         'Position',[0.05 0.60 0.3 0.2]);
    %
    %     h.uploaddependentvarstr = uicontrol(h.panel10 ,...
    %         'Style','pushbutton',...
    %         'String','Upload',...
    %         'Units', 'normalized', ...
    %         'Position',[0.45 0.65 0.3 0.2]);
    %
    %     h.uploaddependentvarstrlabel = uicontrol(h.panel10 ,...
    %         'Style','edit',...
    %         'String',' ',...
    %         'Units', 'normalized', ...
    %         'Position',[0.77 0.65 0.1 0.2]);
    %
    %     h.uploadindependentvar = uicontrol(h.panel10,...
    %         'Style','text',...
    %         'String','Independent Variables',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.20 0.4 0.3]);
    %
    %     h.uploadindependentvarstr = uicontrol(h.panel10 ,...
    %         'Style','pushbutton',...
    %         'String','Upload',...
    %         'Units', 'normalized', ...
    %         'Position',[0.45 0.35 0.3 0.2]);
    %
    %     h.uploadindependentvarstrlabel = uicontrol(h.panel10 ,...
    %         'Style','edit',...
    %         'String',' ',...
    %         'Units', 'normalized', ...
    %         'Position',[0.77 0.35 0.1 0.2]);
    %
    %     h.rundata = uicontrol(h.panel4 ,...
    %         'Style','pushbutton',...
    %         'String','Run',...
    %         'Units', 'normalized', ...
    %         'Position',[0.2 0.025 0.6 0.035]);
    %
    %     % Button Functions
    %     %----------------------------------------------------------------------
    %     set(h.uploaddependentvarstr, 'callback',{@uploaddependentvarstrproc, h});
    %     set(h.uploadindependentvarstr, 'callback',{@uploadindependentvarstrproc, h});
    %     set(h.rundata, 'callback',{@rundataproctimeregression, h});
    
else
    % Do Nothing
end

guidata(hObject,h)

end