% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceeddataassociationproc(hObject, eventdata, h)

% Initialize Variables
% Extract Handle Data
%-------------------------------------
valuesample1 = get(h.sample1, 'Value');
valuesample2 = get(h.sample2, 'Value');
% valuesample3 = get(h.sample3, 'Value');
valuesample4 = get(h.sample4, 'Value');

% Decision Algorithm
%-------------------------------------
if valuesample1 == 1 && valuesample2 == 0 && valuesample4 == 0
    % Both are Ordinal
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    
    fprintf('------------------- \n');
    fprintf('Ordinal Data \n');
    fprintf('------------------- \n');
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.ordinalinp1 = uicontrol(h.panel10,...
        'Style','text',...
        'String','Ordinal Data 1',...
        'Units', 'normalized', ...
        'Position',[0.05 0.60 0.3 0.2]);
    
    h.ordinalinp1val = uicontrol(h.panel10,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
    h.ordinalinp2 = uicontrol(h.panel10,...
        'Style','text',...
        'String','Ordinal Data 2',...
        'Units', 'normalized', ...
        'Position',[0.05 0.20 0.3 0.3]);
    
    h.ordinalinp2val = uicontrol(h.panel10,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.3 0.2]);
    
    h.ordinalinp1vallabel = uicontrol(h.panel10,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.65 0.1 0.2]);
    
    h.ordinalinp2vallabel = uicontrol(h.panel10,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.35 0.1 0.2]);
    
    h.runordinaldata = uicontrol(h.panel4,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    set(h.ordinalinp1val, 'callback',{@ordinalinp1valupload, h});
    set(h.ordinalinp2val, 'callback',{@ordinalinp2valupload, h});
    set(h.runordinaldata, 'callback',{@runordinaldataproc, h});
    
elseif valuesample1 == 0 && valuesample2 == 1 && valuesample4 == 0
    % Both are Continuous
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    
    fprintf('------------------- \n');
    fprintf('Continuous Data \n');
    fprintf('------------------- \n');
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.continuousinp1 = uicontrol(h.panel10 ,...
        'Style','text',...
        'String','Continuous Data 1',...
        'Units', 'normalized', ...
        'Position',[0.05 0.60 0.3 0.2]);
    
    h.continuousinp1val = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
    h.continuousinp2 = uicontrol(h.panel10 ,...
        'Style','text',...
        'String','Continuous Data 2',...
        'Units', 'normalized', ...
        'Position',[0.05 0.20 0.3 0.3]);
    
    h.continuousinp2val = uicontrol(h.panel10 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.3 0.2]);
    
    h.continuousinp1vallabel = uicontrol(h.panel10 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.65 0.1 0.2]);
    
    h.continuousinp2vallabel = uicontrol(h.panel10 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.35 0.1 0.2]);
    
    h.runcontinuousdata = uicontrol(h.panel4,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    set(h.continuousinp1val, 'callback',{@continuousinp1valupload, h});
    set(h.continuousinp2val, 'callback',{@continuousinp2valupload, h});
    set(h.runcontinuousdata, 'callback',{@runcontinuousdataproc, h});
    
% elseif valuesample1 == 0 && valuesample2 == 0 && valuesample3 == 1 && valuesample4 == 0
%     % Both are Nominal
%     
%     % Delete existing handles
%     %----------------------------------------------
%     panel10_label = findall(h.panel4,'title', 'B');
%     panel11_label = findall(h.panel4,'title', 'C');
%     delete(panel10_label);
%     delete(panel11_label);
%     
%     
%     fprintf('------------------- \n');
%     fprintf('Nominal Data \n');
%     fprintf('------------------- \n');
%     
%     h.panel10 = uipanel(h.panel4,...
%         'Title','B',...
%         'Position',[.05 .58 .9 .2]);
%     
%     h.cbinp1 = uicontrol(h.panel10,...
%         'Style','text',...
%         'String','Nominal Data 1',...
%         'Units', 'normalized', ...
%         'Position',[0.05 0.60 0.3 0.2]);
%     
%     h.cbinp1val = uicontrol(h.panel10,...
%         'Style','pushbutton',...
%         'String','Upload Data',...
%         'Units', 'normalized', ...
%         'Position',[0.45 0.65 0.3 0.2]);
%     
%     h.cbinp2 = uicontrol(h.panel10,...
%         'Style','text',...
%         'String','Nominal Data 2',...
%         'Units', 'normalized', ...
%         'Position',[0.05 0.20 0.3 0.3]);
%     
%     h.cbinp2val = uicontrol(h.panel10,...
%         'Style','pushbutton',...
%         'String','Upload Data',...
%         'Units', 'normalized', ...
%         'Position',[0.45 0.35 0.3 0.2]);
%     
%     h.cbinp1vallabel = uicontrol(h.panel10,...
%         'Style','edit',...
%         'String',' ',...
%         'Units', 'normalized', ...
%         'Position',[0.77 0.65 0.1 0.2]);
%     
%     h.cbinp2vallabel = uicontrol(h.panel10,...
%         'Style','edit',...
%         'String',' ',...
%         'Units', 'normalized', ...
%         'Position',[0.77 0.35 0.1 0.2]);
%     
%     h.runcbdata = uicontrol(h.panel4,...
%         'Style','pushbutton',...
%         'String','Run',...
%         'Units', 'normalized', ...
%         'Position',[0.2 0.025 0.6 0.035]);
%     
%     set(h.cbinp1val, 'callback',{@cbinp1valupload, h});
%     set(h.cbinp2val, 'callback',{@cbinp2valupload, h});
%     set(h.runcbdata, 'callback',{@runcbdataupload, h});
    
elseif valuesample1 == 0 && valuesample2 == 0 && valuesample4 == 1
    % One Continuous & One Binary
    
    % Delete existing handles
    %----------------------------------------------
    panel10_label = findall(h.panel4,'title', 'B');
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel10_label);
    delete(panel11_label);
    
    
    fprintf('------------------- \n');
    fprintf('One Continuous and One Binary Data \n');
    fprintf('------------------- \n');
    
    h.panel10 = uipanel(h.panel4,...
        'Title','B',...
        'Position',[.05 .58 .9 .2]);
    
    h.nominalinp1 = uicontrol(h.panel10,...
        'Style','text',...
        'String','Continuous Data 1',...
        'Units', 'normalized', ...
        'Position',[0.05 0.60 0.3 0.2]);
    
    h.nominalinp1val = uicontrol(h.panel10,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.65 0.3 0.2]);
    
    h.nominalinp2 = uicontrol(h.panel10,...
        'Style','text',...
        'String','Binary Data 2',...
        'Units', 'normalized', ...
        'Position',[0.05 0.20 0.3 0.3]);
    
    h.nominalinp2val = uicontrol(h.panel10,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.35 0.3 0.2]);
    
    h.nominalinp1vallabel = uicontrol(h.panel10,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.65 0.1 0.2]);
    
    h.nominalinp2vallabel = uicontrol(h.panel10,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.77 0.35 0.1 0.2]);
    
    h.runnominaldata = uicontrol(h.panel4,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    set(h.nominalinp1val, 'callback',{@nominalinp1valupload, h});
    set(h.nominalinp2val, 'callback',{@nominalinp2valupload, h});
    set(h.runnominaldata, 'callback',{@runnominaldataproc, h});
    
else
    % Do Nothing
end

guidata(hObject,h);

end