% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function proceedprocprocedure_morethan2(hObject, eventdata, h)

% Get handle values
%----------------------------------------------------
unpaired_val = get(h.proportionunpaired, 'Value');
paired_val = get(h.proportionpaired, 'Value');

% Decision Algorithm
%----------------------------------------------------
if unpaired_val == 1 && paired_val == 0
    
    % Unpaired variables
    %----------------------------------------
    
    % Delete previous labels
    %----------------------------------------
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    % Structure
    %----------------------------------------
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    %     h.radiogroup4 = uibuttongroup(h.panel11,...
    %         'Units','normalized',...
    %         'Position', [0.05 0.03 0.90 0.6]);
    %
    %     h.totalsamplessample1 = uicontrol(h.radiogroup4,...
    %         'Style','text',...
    %         'String','Total Outcomes (Sample 1)',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.70 0.5 0.20]);
    %
    %     h.totalsamplessample1val = uicontrol(h.radiogroup4,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.5 0.80 0.4 0.15]);
    %
    %     h.totalsamplessample2 = uicontrol(h.radiogroup4,...
    %         'Style','text',...
    %         'String','Total Outcomes (Sample 2)',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.56 0.5 0.20]);
    %
    %     h.totalsamplessample2val = uicontrol(h.radiogroup4,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.5 0.63 0.4 0.15]);
    %
    %     h.favoutcomessample1 = uicontrol(h.radiogroup4,...
    %         'Style','text',...
    %         'String','Favourable Outcomes (Sample 1)',...
    %         'Units', 'normalized', ...
    %         'Position',[0.03 0.40 0.4 0.20]);
    %
    %     h.favoutcomessample1val = uicontrol(h.radiogroup4,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.5 0.45 0.4 0.15]);
    %
    %     h.favoutcomessample2 = uicontrol(h.radiogroup4,...
    %         'Style','text',...
    %         'String','Favourable Outcomes (Sample 2)',...
    %         'Units', 'normalized', ...
    %         'Position',[0.03 0.20 0.4 0.20]);
    %
    %     h.favoutcomessample2val = uicontrol(h.radiogroup4,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.5 0.25 0.4 0.15]);
    %
    %     h.alphavallabel = uicontrol(h.radiogroup4,...
    %         'Style','text',...
    %         'String','Alpha value',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.05 0.4 0.1]);
    %
    %     h.alphaval = uicontrol(h.radiogroup4,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.5 0.05 0.4 0.15]);
    %
    %     h.rundata = uicontrol(h.panel4 ,...
    %         'Style','pushbutton',...
    %         'String','Run',...
    %         'Units', 'normalized', ...
    %         'Position',[0.2 0.025 0.6 0.035]);
    %
    %     % Checkbox Callback functions
    %     %---------------------------------------------------------------------
    %     set(h.rundata, 'callback',{@rundatatwosampleproc, h});
    
    h.radiogroup4 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.65 0.90 0.3]);
    
    h.cat1 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Categorical Data',...
        'Units', 'normalized', ...
        'Position',[0.01 0.60 0.5 0.2]);
    
    h.cat1val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.60 0.25 0.25]);
    
    %     h.cat2 = uicontrol(h.radiogroup4 ,...
    %         'Style','text',...
    %         'String','Categorical Data 2',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.60 0.5 0.1]);
    %
    %     h.cat2val = uicontrol(h.radiogroup4 ,...
    %         'Style','pushbutton',...
    %         'String','Upload Data',...
    %         'Units', 'normalized', ...
    %         'Position',[0.45 0.55 0.25 0.2]);
    
    h.cat1value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.60 0.15 0.25],...
        'Max', 100);
    
    %     h.cat2value = uicontrol(h.radiogroup4 ,...
    %         'Style','edit',...
    %         'String',' ',...
    %         'Units', 'normalized', ...
    %         'Position',[0.755 0.55 0.15 0.2]);
    
    %     h.alphavallabel = uicontrol(h.radiogroup4 ,...
    %         'Style','text',...
    %         'String','Alpha value',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.35 0.4 0.1]);
    %
    %     h.alphaval = uicontrol(h.radiogroup4 ,...
    %         'Style','edit',...
    %         'String','',...
    %         'Units', 'normalized', ...
    %         'Position',[0.45 0.35 0.25 0.15]);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Checkbox Callback functions
    %---------------------------------------------------------------------
    set(h.cat1val, 'callback',{@cat1valuploaddataproc_unpaired, h});
    % set(h.cat2val, 'callback',{@cat2valuploaddataproc, h});
    set(h.rundata, 'callback',{@rundata_morethantwosample_proc_unpaired, h});
    
elseif unpaired_val == 0 && paired_val == 1
    
    % Paired variables
    %----------------------------------------
    % Delete previous labels
    %----------------------------------------
    panel11_label = findall(h.panel4,'title', 'C');
    delete(panel11_label);
    
    % Structure
    %----------------------------------------
    h.panel11 = uipanel(h.panel4,...
        'Title','C',...
        'Position',[.05 .08 .9 .5]);
    
    h.radiogroup4 = uibuttongroup(h.panel11,...
        'Units','normalized',...
        'Position', [0.05 0.65 0.90 0.3]);
    
    h.cat1 = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Categorical Data',...
        'Units', 'normalized', ...
        'Position',[0.01 0.60 0.5 0.2]);
    
    h.cat1val = uicontrol(h.radiogroup4 ,...
        'Style','pushbutton',...
        'String','Upload Data',...
        'Units', 'normalized', ...
        'Position',[0.45 0.60 0.25 0.25]);
    
    %     h.cat2 = uicontrol(h.radiogroup4 ,...
    %         'Style','text',...
    %         'String','Categorical Data 2',...
    %         'Units', 'normalized', ...
    %         'Position',[0.01 0.60 0.5 0.1]);
    %
    %     h.cat2val = uicontrol(h.radiogroup4 ,...
    %         'Style','pushbutton',...
    %         'String','Upload Data',...
    %         'Units', 'normalized', ...
    %         'Position',[0.45 0.55 0.25 0.2]);
    
    h.cat1value = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String',' ',...
        'Units', 'normalized', ...
        'Position',[0.755 0.60 0.15 0.25],...
        'Max', 100);
    
    %     h.cat2value = uicontrol(h.radiogroup4 ,...
    %         'Style','edit',...
    %         'String',' ',...
    %         'Units', 'normalized', ...
    %         'Position',[0.755 0.55 0.15 0.2]);
    
    h.alphavallabel = uicontrol(h.radiogroup4 ,...
        'Style','text',...
        'String','Alpha value',...
        'Units', 'normalized', ...
        'Position',[0.01 0.25 0.4 0.25]);
    
    h.alphaval = uicontrol(h.radiogroup4 ,...
        'Style','edit',...
        'String','',...
        'Units', 'normalized', ...
        'Position',[0.45 0.25 0.25 0.25]);
    
    h.rundata = uicontrol(h.panel4 ,...
        'Style','pushbutton',...
        'String','Run',...
        'Units', 'normalized', ...
        'Position',[0.2 0.025 0.6 0.035]);
    
    % Checkbox Callback functions
    %---------------------------------------------------------------------
    set(h.cat1val, 'callback',{@cat1valuploaddataproc_unpaired, h});
    % set(h.cat2val, 'callback',{@cat2valuploaddataproc, h});
    set(h.rundata, 'callback',{@rundata_morethantwosample_proc_paired, h});
    
else
    % Do Nothing
end

guidata(hObject,h);

end