% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function seedetailsproc(hObject, eventdata, h)

h.figure = figure('units','normalized','position',[0.05, 0.05, 0.3, 0.4],...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Name','File and Data Details');

h.panel6 = uipanel('Title','File details',...
    'Position',[.02 .49 .96 .5],...
    'FontSize',10.5,'FontWeight','bold');

h.filenamestring= uicontrol(h.panel6,...
    'Style','text',...
    'String','Filename: ',...
    'Units', 'normalized', ...
    'Position',[0.05, 0.73, 0.2, 0.1],...
    'FontWeight','bold');

h.filenamestring_text= uicontrol(h.panel6,...
    'Style','text',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.3, 0.73, 0.6, 0.1]);

h.filepathstring = uicontrol(h.panel6,...
    'Style','text',...
    'String','Filepath: ',...
    'Units', 'normalized', ...
    'Position',[0.05, 0.60, 0.2, 0.1],...
    'FontWeight','bold');

h.filepathstring_text = uicontrol(h.panel6,...
    'Style','text',...
    'String','',...
    'Units', 'normalized', ...
    'Position',[0.3, 0.40, 0.6, 0.3]);

h.fileext = uicontrol(h.panel6,...
    'Style','text',...
    'String','Extension: ',...
    'Units', 'normalized', ...
    'Position',[0.05, 0.35, 0.2, 0.1],...
    'FontWeight','bold');

h.fileext_val = uicontrol(h.panel6,...
    'Style','text',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.3, 0.35, 0.6, 0.1]);

h.sheets = uicontrol(h.panel6,...
    'Style','text',...
    'String','Sheets: ',...
    'Units', 'normalized', ...
    'Position',[0.05, 0.20, 0.2, 0.1],...
    'FontWeight','bold');

h.sheets_val = uicontrol(h.panel6,...
    'Style','text',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.3, 0.20, 0.6, 0.1]);

h.panel7 = uipanel('Title','Data details',...
    'Position',[.02 .01 .5 .48],...
    'FontSize',10.5,'FontWeight','bold');

% h.sample_size = uicontrol(h.panel7,...
%     'Style','text',...
%     'String','Sample size ',...
%     'Units', 'normalized', ...
%     'Position',[0.05, 0.80, 0.3, 0.1]);

h.colnumber = uicontrol(h.panel7,...
    'Style','text',...
    'String','Variables (Number of columns): ',...
    'Units', 'normalized', ...
    'Position',[0.01, 0.55, 0.75, 0.1]);

h.colnumber_val= uicontrol(h.panel7,...
    'Style','text',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.75, 0.55, 0.2, 0.1]);

h.rownumber = uicontrol(h.panel7,...
    'Style','text',...
    'String','Sample Size (Number of rows): ',...
    'Units', 'normalized', ...
    'Position',[0.01, 0.40, 0.75, 0.1]);

h.rownumber_val= uicontrol(h.panel7,...
    'Style','text',...
    'String',' ',...
    'Units', 'normalized', ...
    'Position',[0.75, 0.40, 0.2, 0.1]);

h.panel8 = uipanel('Title','Variables',...
    'Position',[.53 .01 .45 .48],...
    'FontSize',10.5,'FontWeight','bold');

% h.var_sample = uicontrol(h.panel8,...
%     'Style','text',...
%     'String','Variables:',...
%     'Units', 'normalized', ...
%     'Position',[0.05, 0.80, 0.3, 0.1]);
% 
% h.var_sample_num = uicontrol(h.panel8,...
%     'Style','text',...
%     'String',' ',...
%     'Units', 'normalized', ...
%     'Position',[0.35, 0.80, 0.3, 0.1]);

h.var_sample_val = uicontrol(h.panel8,...
    'Style','edit',...
    'String',' ',...
    'min',0,'max',10000,'enable','inactive',...
    'Units', 'normalized', ...
    'Position',[0.05, 0.100, 0.9, 0.8]);

% Value additions
%-------------------------------------------------------------------------

% Fill the values
pathcomplete = getappdata(0, 'getbrowsedir'); % path of the excel file
[filepath,name,ext] = fileparts(pathcomplete); % extract name and path
[~, sheets] = xlsfinfo(pathcomplete); % count number of sheets in an excel
numsheets = length(sheets); % number of sheets in number
[~, ~, raw] = xlsread(pathcomplete); % read excel sheet
data = xlsread(pathcomplete); % read data only for excel sheet
[row, col] = size(data); % calculate number of rows and columns
var_arr = raw(1,:); % call variable names
numvar = length(var_arr); % number of variables

% Set the values on the GUI
set(h.filenamestring_text, 'String', name);
set(h.filepathstring_text, 'String', filepath);
set(h.sheets_val, 'String', numsheets);
set(h.rownumber_val, 'String', row);
set(h.colnumber_val, 'String', col);
set(h.var_sample_val, 'String', var_arr);
set(h.fileext_val, 'String', ext);


end