% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function start

clc;
clear;
close all;

%-----------Text message--------------------------
% Introducttory message
%--------------------------------------------------
intro_message;

%-----------Interface-1----------------------------
% Interface : Primary Pipeline
%--------------------------------------------------

h.figure = figure('units','normalized',...
    'position',[0.05, 0.05, 0.5, 0.65],...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Name','NINS-STAT-ver.1.0');

% Note Panel 1 has been replaced to Panel 13
% Note Panel 2 has been removed

h.panel13 = uipanel('Title','Initialize',...
    'Position',[.01 .008 .2 0.98],...
    'FontSize',10.5,...
    'FontWeight','bold');

h.panel3 = uipanel('Title','Objectives',...
    'Position',[.215 .008 .3 .98],...
    'FontSize',10.5,...
    'FontWeight','bold');

h.panel4 = uipanel('Title','Analysis',...
    'Position',[.52 .008 .47 .98],...
    'FontSize',10.5,...
    'FontWeight','bold');

h.panel14 = uipanel(h.panel13,'Title','Data import',...
    'Position',[.03 .73 .95 .25],...
    'FontSize',9,...
    'FontWeight','bold');

h.browse = uicontrol(h.panel14,...
    'Style','pushbutton',...
    'String','Browse',...
    'Units', 'normalized', ...
    'Position',[0.02 0.75 0.95 0.15],...
    'FontWeight','bold');

h.dirtype = uicontrol(h.panel14,...
    'Style','text',...
    'String','Filename selected:',...
    'Units', 'normalized', ...
    'Position',[0.05 0.45 0.9 0.2]);

h.seedetails = uicontrol(h.panel14,...
    'Style','pushbutton',...
    'String','Details',...
    'Units', 'normalized', ...
    'Position',[0.02 0.05 0.95 0.15],...
    'FontWeight','bold');

h.panel15 = uipanel(h.panel13,'Title','Automation Pipeline',...
    'Position',[.03 .565 .95 .15],...
    'FontSize',9,...
    'FontWeight','bold');

h.researchquestion = uicontrol(h.panel15,...
    'Style', 'popup', ...
    'Units', 'normalized', ...
    'Position', [0.05, 0.80, 0.9, 0.1], ...
    'String', {'Cross Sectional Study','Cohort Study','Case Control Study','Clinical Trial'});

h.gobutton  = uicontrol(h.panel15,...
    'Style','pushbutton',...
    'String','Begin',...
    'Units', 'normalized', ...
    'Position',[0.02 0.18 0.95 0.28],...
    'FontWeight','bold');

h.panel17 = uipanel(h.panel13,'Title','Descriptive analysis',...
    'Position',[.03 .40 .95 .15],...
    'FontSize',9,...
    'FontWeight','bold');

h.descriptive_analysis = uicontrol(h.panel17,...
    'Style', 'popup', ...
    'Units', 'normalized', ...
    'Position', [0.05, 0.80, 0.9, 0.1], ...
    'String', {'Continuous','Categorical'});

h.gobutton_descriptive_analysis  = uicontrol(h.panel17,...
    'Style','pushbutton',...
    'String','Begin',...
    'Units', 'normalized', ...
    'Position',[0.02 0.18 0.95 0.28],...
    'FontWeight','bold');

h.panel16 = uipanel(h.panel13,'Title','Data visualization',...
    'Position',[.03 .23 .95 .15],...
    'FontSize',9,...
    'FontWeight','bold');

h.datavartype = uicontrol(h.panel16,...
    'Style', 'popup', ...
    'Units', 'normalized', ...
    'Position', [0.05, 0.80, 0.9, 0.1], ...
    'String', {'Continuous','Categorical'});

h.gobutton_data_visualization  = uicontrol(h.panel16,...
    'Style','pushbutton',...
    'String','Begin',...
    'Units', 'normalized', ...
    'Position',[0.02 0.18 0.95 0.28],...
    'FontWeight','bold');

h.panel18 = uipanel(h.panel13,'Title','Help',...
    'Position',[.03 .07 .95 .15],...
    'FontSize',9,...
    'FontWeight','bold');

h.resetbutton  = uicontrol(h.panel18,...
    'Style','pushbutton',...
    'String','Reset',...
    'Units', 'normalized', ...
    'Position',[0.02 0.50 0.95 0.30],...
    'FontWeight','bold');

h.help = uicontrol(h.panel18,...
    'Style','pushbutton',...
    'String','Manual',...
    'Units', 'normalized', ...
    'Position',[0.02 0.10 0.95 0.30],...
    'FontWeight','bold');

h.panel19 = uipanel(h.panel13,...
    'Position',[.03 .01 .95 .05],...
    'FontSize',9,...
    'FontWeight','bold');

h.textcreator = uicontrol(h.panel19,...
    'Style','text',...
    'String','@ Developed by NINS-LAB',...
    'Units', 'normalized', ...
    'FontSize',9,...
    'Position',[0.01 0.1 0.9 1]);

% -------------------------------------------------
% ---------- Button-Functions ---------------------
% -------------------------------------------------

set(h.browse, 'callback', {@browseproc, h}); % Procedure for browsing of data
set(h.seedetails, 'callback', {@seedetailsproc, h}); % Procedure for observing the details of the excel sheet
set(h.gobutton, 'callback', {@gobuttonproc, h}); % Procedure for automated pipeline
set(h.gobutton_data_visualization, 'callback', {@gobutton_data_visualization_proc, h}); % Procedure for implementing data visualization toolboxes
set(h.gobutton_descriptive_analysis, 'callback', {@gobutton_descriptive_analysis_proc, h}); % Procedure for implementing descriptive analysis
set(h.resetbutton, 'callback', {@resetbuttonproc ,h}); % Procedure for resetting the GUI
set(h.help, 'callback', {@helpproc, h}); % Procedure for showing the manual

fprintf('Interface Initialize \n');
fprintf('######################################### \n\n');
fprintf('Starting Analysis \n');
fprintf('----------------------------------------- \n');

end
