% NINS-STAT Graphical User Interface
% start.m function starts the entire
% interface.
%
% Final revision date : 11th August 2021

% Author:
% Dr. Pravat K. Mandal
% Neuroimaging and Neurospectroscopy Lab,
% National Brain Research Centre,
% Manesar, India

function survivalstudyobjectivelist(hObject, eventdata, h)

% Available Objectives :
% 1) Survival 
% 2) Predictors of an Outcome (Regression Analysis)

h.radiogroup = uibuttongroup(h.panel3,...
     'Units','normalized',...
     'Position', [0.1 0.07 0.8 0.9]);
 
 h.enterdirectory = uicontrol(h.radiogroup,...
    'Style','text',...
    'String','Recommended',...
    'Units', 'normalized', ...
    'Position',[0.05, 0.86, 0.5, 0.1]);

 h.survivaloption = uicontrol(h.radiogroup ,...
    'Style','radiobutton',...
    'String',' Survival',...
    'Units', 'normalized', ...
    'Position',[0.2 0.82 0.9 0.1],...
    'HandleVisibility','off');

h.regressionoption = uicontrol(h.radiogroup ,...
    'Style','radiobutton',...
    'String',' Regression',...
    'Units', 'normalized', ...
    'Position',[0.2 0.76 0.9 0.1],...
    'HandleVisibility','off');

h.enterdirectory = uicontrol(h.radiogroup,...
    'Style','text',...
    'String','Optional',...
    'Units', 'normalized', ...
    'Position',[0.01 0.65 0.4 0.1]);

h.proportionoption = uicontrol(h.radiogroup,...
    'Style','radiobutton',...
    'String',' Proportions',...
    'Units', 'normalized', ...
    'Position',[0.2 0.59 0.9 0.1],...
    'HandleVisibility','off');

h.meanoption = uicontrol(h.radiogroup ,...
    'Style','radiobutton',...
    'String',' Mean',...
    'Units', 'normalized', ...
    'Position',[0.2 0.53 0.9 0.1],...
    'HandleVisibility','off');

h.associationoption = uicontrol(h.radiogroup ,...
    'Style','radiobutton',...
    'String',' Association',...
    'Units', 'normalized', ...
    'Position',[0.2 0.47 0.9 0.1],...
    'HandleVisibility','off');

h.agreementoption = uicontrol(h.radiogroup ,...
    'Style','radiobutton',...
    'String',' Agreement',...
    'Units', 'normalized', ...
    'Position',[0.2 0.41 0.9 0.1],...
    'HandleVisibility','off');

h.diagnosticoption = uicontrol(h.radiogroup ,...
    'Style','radiobutton',...
    'String',' Diagnostic',...
    'Units', 'normalized', ...
    'Position',[0.2 0.34 0.9 0.1],...
    'HandleVisibility','off');

h.startbutton  = uicontrol(h.panel3,...
    'Style','pushbutton',...
    'String','Proceed',...
    'Units', 'normalized', ...
    'Position',[0.2 0.025 0.6 0.035]);

set(h.startbutton, 'callback', {@startproc, h});

end